### ISSUE TITLE
Transaction tracking/progress bar

### ISSUE THREAD

**Issue by Mury12** [Pollum-io/solana-governance-ui#20]
Develop a generic component and hooks to track the transaction progress and show to the user

 - [ ] Create a sufficiently generic component to fit in a lib
 - [ ] Create the hooks to track the transaction status
 - [ ] Modify `sendTransactions` to update the states
 - [ ] Understand if transactions are parallel or sequential and identify which transaction has failed
 - [ ] Identify if transaction failure is due to method timeout or network error
 - [ ] Store state to redo the failed transactions
 - [x] ~~Promise Events~~

It will probably need to re-create the `sendTransactions` method bound with the component to perfectly fit in the requirements
